language: node_js
node_js: "8"
script: yarn build:full
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  repo: "sbergot.github.io"
  target-branc: master
  on:
    branch: master